language: c
compiler:
    - gcc
dist: focal
cache: ccache

git:
  depth: 10
  quiet: false

if: tag IS blank

branches:
  only:
    - /^.*-main$/
    - /^.*-travis$/

install:
    - sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu focal main'
    - sudo apt-get update -qq
    - sudo apt-get install -qq ccache libssl-dev u-boot-tools python-mako debhelper fakeroot gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu make device-tree-compiler
script:
    - export PATH=/usr/lib/ccache:$PATH
    - bash build.sh importconfig
    - bash build.sh build
    - bash build.sh cryptodev
    - bash build.sh pack_debs
    - bash build.sh pack
    - sed -i 's/#\(board=bpi-r64\)/\1/' build.conf #change board to r64
    - bash build.sh importconfig
    - bash build.sh build
    - bash build.sh cryptodev
    - bash build.sh pack_debs
    - bash build.sh pack
before_deploy:
    # Set up git user name and tag this commit
    - git config --local user.name "Frank Wunderlich"
    - git config --local user.email "frank-w@public-files.de"
    - export TRAVIS_TAG=${TRAVIS_TAG:-"CI-BUILD-$(date +'%Y%m%d_%H%M%S')-$(git log --format=%h -1)"}
    - git tag $TRAVIS_TAG
deploy:
    provider: releases
    token: $GITHUB_TOKEN
    file_glob: true
    file:
    - "../SD/*"
    - "../*.deb"
    - "bpi-r64-*.itb"
    name: $TRAVIS_BRANCH-$(date +'%Y%m%d%H%M%S')
    skip_cleanup: true
    cleanup: false
    on:
        all_branches: true
