cmd_drivers/misc/mediatek/connectivity/common/conn_soc/core/dbg_core.o := arm-linux-gnueabihf-gcc -Wp,-MD,drivers/misc/mediatek/connectivity/common/conn_soc/core/.dbg_core.o.d  -nostdinc -isystem /usr/lib/gcc-cross/arm-linux-gnueabihf/9/include -I./arch/arm/include -Iarch/arm/include/generated/uapi -Iarch/arm/include/generated  -Iinclude -I./arch/arm/include/uapi -Iarch/arm/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE -fno-dwarf2-cfi-asm -fno-omit-frame-pointer -mapcs -mno-sched-prolog -fno-ipa-sra -mabi=aapcs-linux -mno-thumb-interwork -mfpu=vfp -funwind-tables -marm -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -fno-delete-null-pointer-checks -Wno-maybe-uninitialized -Wno-frame-address -Wno-format-truncation -Wno-format-overflow -Wno-int-in-bool-context -Wno-attribute-alias -O2 --param=allow-store-data-races=0 -DCC_HAVE_ASM_GOTO -Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable -Wno-unused-const-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -g -pg -Wdeclaration-after-statement -Wno-pointer-sign -Wno-stringop-truncation -fno-strict-overflow -fno-merge-all-constants -fmerge-constants -fno-stack-check -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Wno-packed-not-aligned -Werror -I./drivers/misc/mediatek/include/mt-plat/ -D MTK_WCN_REMOVE_KERNEL_MODULE -D WMT_IDC_SUPPORT=0 -D MTK_WCN_WMT_STP_EXP_SYMBOL_ABSTRACT -Werror -I./drivers/misc/mediatek/include/mt-plat//include -Werror -I./drivers/misc/mediatek/include/mt-plat -Idrivers/misc/mediatek/connectivity/common/conn_soc/linux/include -Idrivers/misc/mediatek/connectivity/common/conn_soc/linux/pri/include -Idrivers/misc/mediatek/connectivity/common/conn_soc/core/include -Idrivers/misc/mediatek/connectivity/common/conn_soc/include -Idrivers/misc/mediatek/connectivity/common/conn_soc/../common_detect -I./drivers/misc/mediatek/btif/common/inc -I./drivers/misc/mediatek/eccci/ -I./drivers/misc/mediatek/eccci/ -I./drivers/misc/mediatek/eemcs/ -I./drivers/misc/mediatek/conn_md/include -Idrivers/misc/mediatek/connectivity/common/conn_soc/core/../linux/include -Idrivers/misc/mediatek/connectivity/common/conn_soc/core/../linux/pri/include -Idrivers/misc/mediatek/connectivity/common/conn_soc/core/../core/include -Idrivers/misc/mediatek/connectivity/common/conn_soc/core/../include -Idrivers/misc/mediatek/connectivity/common/conn_soc/core/../../common_detect -I./drivers/misc/mediatek/btif/common/inc    -D"KBUILD_STR(s)=$(pound)s" -D"KBUILD_BASENAME=KBUILD_STR(dbg_core)"  -D"KBUILD_MODNAME=KBUILD_STR(dbg_core)" -c -o drivers/misc/mediatek/connectivity/common/conn_soc/core/dbg_core.o drivers/misc/mediatek/connectivity/common/conn_soc/core/dbg_core.c

source_drivers/misc/mediatek/connectivity/common/conn_soc/core/dbg_core.o := drivers/misc/mediatek/connectivity/common/conn_soc/core/dbg_core.c

deps_drivers/misc/mediatek/connectivity/common/conn_soc/core/dbg_core.o := \

drivers/misc/mediatek/connectivity/common/conn_soc/core/dbg_core.o: $(deps_drivers/misc/mediatek/connectivity/common/conn_soc/core/dbg_core.o)

$(deps_drivers/misc/mediatek/connectivity/common/conn_soc/core/dbg_core.o):
