cmd_drivers/misc/mediatek/connectivity/wlan/gen2/mgmt/rlm_protection.o := arm-linux-gnueabihf-gcc -Wp,-MD,drivers/misc/mediatek/connectivity/wlan/gen2/mgmt/.rlm_protection.o.d  -nostdinc -isystem /usr/lib/gcc-cross/arm-linux-gnueabihf/9/include -I./arch/arm/include -Iarch/arm/include/generated/uapi -Iarch/arm/include/generated  -Iinclude -I./arch/arm/include/uapi -Iarch/arm/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE -fno-dwarf2-cfi-asm -fno-omit-frame-pointer -mapcs -mno-sched-prolog -fno-ipa-sra -mabi=aapcs-linux -mno-thumb-interwork -mfpu=vfp -funwind-tables -marm -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -fno-delete-null-pointer-checks -Wno-maybe-uninitialized -Wno-frame-address -Wno-format-truncation -Wno-format-overflow -Wno-int-in-bool-context -Wno-attribute-alias -O2 --param=allow-store-data-races=0 -DCC_HAVE_ASM_GOTO -Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable -Wno-unused-const-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -g -pg -Wdeclaration-after-statement -Wno-pointer-sign -Wno-stringop-truncation -fno-strict-overflow -fno-merge-all-constants -fmerge-constants -fno-stack-check -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Wno-packed-not-aligned -Werror -I./drivers/misc/mediatek/include/mt-plat/ -D MTK_WCN_REMOVE_KERNEL_MODULE -D WMT_IDC_SUPPORT=0 -D MTK_WCN_WMT_STP_EXP_SYMBOL_ABSTRACT -D MTK_WCN_BUILT_IN_DRIVER -DLINUX -DMT6628 -DCFG_SUPPORT_AGPS_ASSIST=1 -DCFG_SUPPORT_TSF_USING_BOOTTIME=1 -DCFG_P2P_LEGACY_COEX_REVISE=1 -DARP_MONITER_ENABLE=1 -DCFG_SUPPORT_WAPI=1 -DCFG_SUPPORT_MCC=1 -DCFG_SUPPORT_XLOG=0 -DCFG_SUPPORT_AEE=0 -DCFG_SUPPORT_HOTSPOT_2_0=0 -DCFG_HS20_DEBUG=0 -DCFG_ENABLE_GTK_FRAME_FILTER=0 -DCFG_SUPPORT_MET_PROFILING=0 -DCFG_TC1_FEATURE=0 -DCFG_SRAM_SIZE_OPTION=0 -D_HIF_SDIO=1 -DDBG=0 -Idrivers/misc/mediatek/connectivity/wlan/gen2/os -Idrivers/misc/mediatek/connectivity/wlan/gen2/os/linux/include -Idrivers/misc/mediatek/connectivity/wlan/gen2/os/linux/hif/ahb/include -Idrivers/misc/mediatek/connectivity/wlan/gen2/include -Idrivers/misc/mediatek/connectivity/wlan/gen2/include/nic -Idrivers/misc/mediatek/connectivity/wlan/gen2/include/mgmt -I./drivers/misc/mediatek/base/power/include -I./drivers/misc/mediatek/include/    -D"KBUILD_STR(s)=$(pound)s" -D"KBUILD_BASENAME=KBUILD_STR(rlm_protection)"  -D"KBUILD_MODNAME=KBUILD_STR(wlan_gen2)" -c -o drivers/misc/mediatek/connectivity/wlan/gen2/mgmt/rlm_protection.o drivers/misc/mediatek/connectivity/wlan/gen2/mgmt/rlm_protection.c

source_drivers/misc/mediatek/connectivity/wlan/gen2/mgmt/rlm_protection.o := drivers/misc/mediatek/connectivity/wlan/gen2/mgmt/rlm_protection.c

deps_drivers/misc/mediatek/connectivity/wlan/gen2/mgmt/rlm_protection.o := \

drivers/misc/mediatek/connectivity/wlan/gen2/mgmt/rlm_protection.o: $(deps_drivers/misc/mediatek/connectivity/wlan/gen2/mgmt/rlm_protection.o)

$(deps_drivers/misc/mediatek/connectivity/wlan/gen2/mgmt/rlm_protection.o):
